apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekEwTVRZeQpNak0wTkRCYUZ3MDBNekEwTVRZeU1qTTBOREJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEQnRTaTh5L3BlUjAwejZQaHNPNFVQeDVISDUrdUpqVGovVnQ1WmhGRnpaaHV4Mzl2cApPMGxJRHFvSDNrdVBERW5SVHZYN0R6U2d0QzVLQm1DTFJtNVFYaG9adjB3TDEzQ3NneXNVcVBuNmswUDd0ejBzCmRaSm9EUjJrS0R0V0V4WHVjVkFqSisreDRBV0tRb0hGSFdJQ2JPWWtLZE5VRmpQcUZZNFh1Q1FjTzJ2V3Irem4KcFRrU3lXbTJkSm9vbG9KVDcyais0cDZHYUpYTml3Z0U0Y0dxTjVoQUg5L3NhWVBHS0doN2lBcEVpY1hzdTVESgoyYmFhRkg4K0ZjdnBJTjJheVJPZ3FJcENNK3Ewa2czcWpVNkJsTW1KQk5id3JwcjRiZk9hWEc3MmFrSThrRWxZCmV4dkJjQzAvVjRqdDlGREw3eHEvZDBuSEtxQmJialhwVkJ6N0FnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNYZUlsbi9rSEp5b3BKL0c5Ugo4MDBzRC9EZ1N6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFHWTgwMDlzTlVLRlZoYlkxV2pRaHljZmorK25NCnNIRHhocDVvQkIvcFplbzFQT1lKcXVLZnhNV3RDVUtjcFExSVp4UVlkekFCSkhZWDdja2J3Q0l5ZEwwSG42N2QKaVBUaWNsSmtmNDFScDJSdzZvQVZwWGxic21vUlduYncvcDhEZHFPbkEvdHpkODlFcWhIMVlvUGhENTlkZXBxZwo1cytIRnVKRGhvS2JkT05weVFSam1lUmlIbEtSR1YvaVJYOXkvVk9wcVQ4QnlDTzlrb0hqaWoydUJTZ3BoNDlhCjRMU1R0aDFSQ3RrVkpadWdLUWtvdTB4aEJ0S0V2ZDJFNC9EYnp6SkVXd1RWV1NNVlY4UzlGemc3clROWEszSy8KZnExNnh5cXphSWM1cDBNMldvWEozOXBmUGUvV0pZSDRHZHlVVVBIbUtDMXZzNTVNdEhicE14OGRiZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://09d4f4dd-9b74-4f16-9c8a-9f382132c130.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_dc15f5b2b3f18594f89bcaf1794f0474179c54452371fd6bc2ab64c4d1ab2a32
